name: zemingo_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  # DI
  get_it: ^7.6.6
  injectable: ^2.3.2

  url_launcher: ^6.3.0

  # Navigation
  auto_route: ^7.8.4

  # Parsing
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0

  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  xml2json: ^6.2.3
  xml: ^6.5.0
  stream_transform: ^2.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  flutter_gen_runner: ^5.4.0
  auto_route_generator: ^7.3.2
  freezed: ^2.4.6

flutter:


  uses-material-design: true
